name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Linting job
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install flake8 for linting
        run: pip install flake8

      - name: Run flake8 linter
        run: flake8 . --exit-zero

  # Build Docker Image and push to Docker Hub
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg SECRET_KEY=${{ secrets.MY_SECRET_KEY }} \
            -f Dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/my_project:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my_project:latest

  # Testing job with PostgreSQL service
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:17
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5435:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Database to be Ready
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5435 -U test_user && break || sleep 5;
          done

      - name: Run Django Tests
        env:
          DATABASE_URL: postgres://test_user:test_password@localhost:5435/test_db
          SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          DB_HOST: localhost
          DB_PORT: 5435
        run: |
          python ./todo_project/manage.py makemigrations --no-input
          python ./todo_project/manage.py migrate --no-input
          python ./todo_project/manage.py test
