version: '3.8'

services:
  db:
    image: postgres:13
    container_name: todo_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5440:5432" 

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: todo_django
    command: >
      sh -c "
      while ! pg_isready -h db -p 5432 -U ${DB_USER}; do sleep 1; done;
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn todo_project.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8410:8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: todo_nginx
    depends_on:
      - web
    volumes:
      - static:/app/staticfiles
    ports:
      - "8600:80" 

  mailhog:
    image: mailhog/mailhog
    container_name: todo_mailhog
    ports:
      - "9330:1125"
      - "8030:8025"

volumes:
  postgres_data:
  static:
