# Use a slim Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Install dependencies, including netcat-openbsd and postgresql-client for pg_isready
RUN apt-get update && \
    apt-get install -y netcat-openbsd postgresql-client && \
    rm -rf /var/lib/apt/lists/*

# Copy only the requirements file to leverage Docker cache
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project files into the container
COPY . .

# Set the working directory to the Django project folder
WORKDIR /app/todo_project

# Collect static files
RUN python manage.py collectstatic --noinput

# Expose the port
EXPOSE 8000

# Command to run the application
CMD ["gunicorn", "todo_project.wsgi:application", "--bind", "0.0.0.0:8000"]
