version: '3.8'

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"  # Expose port 8000 for the Django app
    volumes:
      - .:/app
      - static_volume:/app/static  # Volume for static files
    depends_on:
      - db
      - mailhog
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - MAILHOG_SMTP_HOST=${MAILHOG_SMTP_HOST}
      - MAILHOG_SMTP_PORT=${MAILHOG_SMTP_PORT}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"  # Expose PostgreSQL port for host access (if needed)

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"  # Mailhog web UI for inspecting emails
      - "1025:1025"  # Mailhog SMTP server

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8600:80"  # Expose nginx port for reverse proxy
    depends_on:
      - web

volumes:
  db_data:
  static_volume:
