services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8410:8000"
    volumes:
      - .:/daniel-todo-project
      - static_volume:/daniel-todo-project/staticfiles
    depends_on:
      - db
      - mailhog
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - MAILHOG_SMTP_HOST=${MAILHOG_SMTP_HOST}
      - MAILHOG_SMTP_PORT=${MAILHOG_SMTP_PORT}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    networks:
      - my_custom_network

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5500:5432"
    networks:
      - my_custom_network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8126:8025"  # Changed to avoid conflict
      - "1028:1025"  # Changed to avoid conflict
    networks:
      - my_custom_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8600:80"
    depends_on:
      - web
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

volumes:
  db_data:
  static_volume:
