name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install flake8 and plugins
        run: pip install flake8 flake8-bugbear flake8-import-order

      - name: Run flake8 linter
        run: flake8 .

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -f Dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/todo_project:latest . \
            --progress=plain

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/todo_project:latest

  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5435:5432
        options: >-
          --health-cmd "pg_isready -h localhost -p 5435 -d mydatabase -U myuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Database to be Ready
        run: |
          for i in {1..20}; do
            pg_isready -h localhost -p 5435 -U myuser -d mydatabase && break || sleep 5;
          done

      - name: Run Django tests
        env:
          DATABASE_URL: postgres://myuser:mypassword@localhost:5435/mydatabase
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          python manage.py makemigrations --no-input
          python manage.py migrate --no-input
          python manage.py collectstatic --noinput
          python manage.py test
